export const MODULE_NAME = 'mp'

/* MUTATIONS */
export const START_FIND_PREFERENCE = 'startFindPreference'
export const START_FIND_PREFERENCE_MUTATION = `${MODULE_NAME}/${START_FIND_PREFERENCE}`

export const SUCCESS_FIND_PREFERENCE = 'successFindPreference'
export const SUCCESS_FIND_PREFERENCE_MUTATION = `${MODULE_NAME}/${SUCCESS_FIND_PREFERENCE}`

export const FAILURE_FIND_PREFERENCE = 'failureFindPreference'
export const FAILURE_FIND_PREFERENCE_MUTATION = `${MODULE_NAME}/${FAILURE_FIND_PREFERENCE}`

/* ACTIONS */
export const FIND_PREFERENCE = 'findPreference'
export const FIND_PREFERENCE_ACTION = `${MODULE_NAME}/${FIND_PREFERENCE}`

/* GETTERS */
export const GET_PREFERENCE = 'getPreference'
export const GET_PREFERENCE_GETTER = `${MODULE_NAME}/${GET_PREFERENCE}`
